-- on unididattica user

BEGIN
    FOR t IN (SELECT table_name FROM all_tables WHERE owner = 'C##UNIDIDATTICA') LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT ON C##UNIDIDATTICA.' || t.table_name || ' TO C##GESTIONESTUDENTI';
    END LOOP;
END;

GRANT INSERT, UPDATE, DELETE ON C##UNIDIDATTICA.student TO C##GESTIONESTUDENTI;
GRANT INSERT, UPDATE, DELETE ON C##UNIDIDATTICA.tuition TO C##GESTIONESTUDENTI;
GRANT INSERT, UPDATE, DELETE ON C##UNIDIDATTICA.enrollment TO C##GESTIONESTUDENTI;
GRANT INSERT, UPDATE, DELETE ON C##UNIDIDATTICA.EnrolledInExtra TO C##GESTIONESTUDENTI;
GRANT INSERT, UPDATE, DELETE ON C##UNIDIDATTICA.Exam TO C##GESTIONESTUDENTI;
GRANT INSERT, UPDATE, DELETE ON C##UNIDIDATTICA.Assignment TO C##GESTIONESTUDENTI;
GRANT INSERT, UPDATE, DELETE ON C##UNIDIDATTICA.StudentAccount TO C##GESTIONESTUDENTI;

GRANT SELECT ON C##UNIDIDATTICA.CourseEnrollmentView TO C##GESTIONESTUDENTI;
GRANT SELECT ON C##UNIDIDATTICA.DegreeProgramView TO C##GESTIONESTUDENTI;
GRANT SELECT ON C##UNIDIDATTICA.DepartmentRefView TO C##GESTIONESTUDENTI;
GRANT SELECT ON C##UNIDIDATTICA.EnrollmentsOfStudentView TO C##GESTIONESTUDENTI;
GRANT SELECT ON C##UNIDIDATTICA.ExamsByStudentView TO C##GESTIONESTUDENTI;
GRANT SELECT ON C##UNIDIDATTICA.PrintNotActiveStudentView TO C##GESTIONESTUDENTI;
GRANT SELECT ON C##UNIDIDATTICA.PrintNotEnrolledStudentExamsView TO C##GESTIONESTUDENTI;
GRANT SELECT ON C##UNIDIDATTICA.CourseEnrollmentView TO C##GESTIONESTUDENTI;
GRANT SELECT ON C##UNIDIDATTICA.PrintStudentInComplianceView TO C##GESTIONESTUDENTI;
GRANT SELECT ON C##UNIDIDATTICA.StudentCredentialsView TO C##GESTIONESTUDENTI;
GRANT SELECT ON C##UNIDIDATTICA.StudentTuitionsView TO C##GESTIONESTUDENTI;

GRANT EXECUTE ON C##UNIDIDATTICA.CheckUnpaidTuition TO C##GESTIONESTUDENTI;
GRANT EXECUTE ON C##UNIDIDATTICA.CreateExamForEnrollment TO C##GESTIONESTUDENTI;
GRANT EXECUTE ON C##UNIDIDATTICA.DeleteAssociatedEnrollmentsProc TO C##GESTIONESTUDENTI;
GRANT EXECUTE ON C##UNIDIDATTICA.GetMatriculations TO C##GESTIONESTUDENTI;
GRANT EXECUTE ON C##UNIDIDATTICA.GetMatriculationsInf TO C##GESTIONESTUDENTI;
GRANT EXECUTE ON C##UNIDIDATTICA.GetMatriculationsMed TO C##GESTIONESTUDENTI;

GRANT EXECUTE ON C##UNIDIDATTICA.CheckPrerequisiteFunction TO C##GESTIONESTUDENTI;
GRANT EXECUTE ON C##UNIDIDATTICA.CreditsObtained TO C##GESTIONESTUDENTI;
GRANT EXECUTE ON C##UNIDIDATTICA.GetDepartmentByEmailAndPassword TO C##GESTIONESTUDENTI;
GRANT EXECUTE ON C##UNIDIDATTICA.StudentsPerCourse TO C##GESTIONESTUDENTI;