-- USER SQL
ALTER USER "C##UNIDIDATTICA"
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "C##UNIDIDATTICA" QUOTA UNLIMITED ON "USERS";

-- ROLES
ALTER USER "C##UNIDIDATTICA" DEFAULT ROLE "CONNECT";

-- SYSTEM PRIVILEGES
  GRANT READ ANY TABLE TO "C##UNIDIDATTICA";
  GRANT SELECT ANY DICTIONARY TO "C##UNIDIDATTICA";
  GRANT EXECUTE ANY OPERATOR TO "C##UNIDIDATTICA";
  GRANT DROP ANY OPERATOR TO "C##UNIDIDATTICA";
  GRANT ALTER ANY OPERATOR TO "C##UNIDIDATTICA";
  GRANT CREATE ANY OPERATOR TO "C##UNIDIDATTICA";
  GRANT CREATE OPERATOR TO "C##UNIDIDATTICA";
  GRANT DROP ANY TYPE TO "C##UNIDIDATTICA";
  GRANT ALTER ANY TYPE TO "C##UNIDIDATTICA";
  GRANT CREATE ANY TYPE TO "C##UNIDIDATTICA";
  GRANT CREATE TYPE TO "C##UNIDIDATTICA";
  GRANT DROP ANY TRIGGER TO "C##UNIDIDATTICA";
  GRANT ALTER ANY TRIGGER TO "C##UNIDIDATTICA";
  GRANT CREATE ANY TRIGGER TO "C##UNIDIDATTICA";
  GRANT CREATE TRIGGER TO "C##UNIDIDATTICA";
  GRANT EXECUTE ANY PROCEDURE TO "C##UNIDIDATTICA";
  GRANT DROP ANY PROCEDURE TO "C##UNIDIDATTICA";
  GRANT ALTER ANY PROCEDURE TO "C##UNIDIDATTICA";
  GRANT CREATE ANY PROCEDURE TO "C##UNIDIDATTICA";
  GRANT CREATE PROCEDURE TO "C##UNIDIDATTICA";
  GRANT DROP ANY SEQUENCE TO "C##UNIDIDATTICA";
  GRANT ALTER ANY SEQUENCE TO "C##UNIDIDATTICA";
  GRANT CREATE ANY SEQUENCE TO "C##UNIDIDATTICA";
  GRANT CREATE SEQUENCE TO "C##UNIDIDATTICA";
  GRANT DROP ANY VIEW TO "C##UNIDIDATTICA";
  GRANT CREATE ANY VIEW TO "C##UNIDIDATTICA";
  GRANT CREATE VIEW TO "C##UNIDIDATTICA";
  GRANT DROP ANY SYNONYM TO "C##UNIDIDATTICA";
  GRANT CREATE ANY SYNONYM TO "C##UNIDIDATTICA";
  GRANT CREATE SYNONYM TO "C##UNIDIDATTICA";
  GRANT DROP ANY INDEX TO "C##UNIDIDATTICA";
  GRANT ALTER ANY INDEX TO "C##UNIDIDATTICA";
  GRANT CREATE ANY INDEX TO "C##UNIDIDATTICA";
  GRANT UPDATE ANY TABLE TO "C##UNIDIDATTICA";
  GRANT INSERT ANY TABLE TO "C##UNIDIDATTICA";
  GRANT SELECT ANY TABLE TO "C##UNIDIDATTICA";
  GRANT DROP ANY TABLE TO "C##UNIDIDATTICA";
  GRANT ALTER ANY TABLE TO "C##UNIDIDATTICA";
  GRANT CREATE ANY TABLE TO "C##UNIDIDATTICA";
  GRANT CREATE TABLE TO "C##UNIDIDATTICA";
  GRANT CREATE USER TO "C##UNIDIDATTICA";
  GRANT UNLIMITED TABLESPACE TO "C##UNIDIDATTICA";
  GRANT DROP TABLESPACE TO "C##UNIDIDATTICA";
  GRANT ALTER TABLESPACE TO "C##UNIDIDATTICA";
  GRANT CREATE TABLESPACE TO "C##UNIDIDATTICA";
  GRANT CREATE SESSION TO "C##UNIDIDATTICA";